### PR TITLE
Clean up console errors

### PR DESCRIPTION
**Pull request by icsd01**
Removes comments, adds colors to buttons, fixes console errors

### CODE REVIEW

**Comment by icsd01** [comment]
You're doing gr8

**Comment by icsd01** [comment]
Oops I'm a bad manager, reopened cause I forgot how to use github

**Comment by icsd01** [comment]
> Oops I'm a bad manager, reopened cause I forgot how to use github

it ok Fred, it ok

**Comment by waful** [comment]
what

**Comment by waful** [comment]
you probably should delete branches after merge

**Pull request merged**
